Repository AlexaVanSchaardenburg/whats-cookin, pull requests merged in 2023-06, with the labels that each got.

#53 Feat/post
  src/RecipeRepository.js
  src/apiCalls.js
  src/domUpdates.js
  src/scripts.js
Labels: enhancement

#62 Fix/display filtered recipes
  src/domUpdates.js
  src/scripts.js
Labels: bug

#65 Refactor/style total cost
  dist/index.html
  src/styles.css
  usability-test.md
Labels: bug, enhancement

#77 Feat/UI enhancements
  dist/index.html
  src/RecipeRepository.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#78 Fix/filter saved recipes
  src/domUpdates.js
Labels: bug

#80 refactor: Add non-catch error messaging for POST and getUPdatedUsers
  src/apiCalls.js
Labels: bug, enhancement
